### ISSUE TITLE
Need to deal with line endings

### ISSUE THREAD

**Issue by isaacrlevin** [Evilazaro/MicrosoftDevBox#48]
Hey there! You might want to add a step in your README to handle Windows messing with line endings (for instance if you open with VS Code in WIndows). Something like this will do the trick

```bash
 find src/ -type f -print0 | xargs -P 4 -0 -n 1  dos2unix
````

**Comment by Evilazaro** [comment]
Hey @isaacrlevin , thank you very much for your contribution here. I've been having this issue myself and will add this to the steps in the README file. I hope I can figure out a way of ending this without having go to through this step.
